# Generated by Django 6.0.1 on 2026-01-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
    ]
