# Generated by Django 6.0.1 on 2026-01-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_organization_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
