# Generated by Django 6.0.1 on 2026-01-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type_name',
            field=models.CharField(max_length=50),
        ),
    ]
