# Generated by Django 6.0.1 on 2026-01-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_event_event_type_alter_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
    ]
